### ISSUE TITLE
Failed installing python bindings

### ISSUE THREAD

**Issue by benam2** [flashlight/flashlight#1002]
I have installed all the dependencies mentioned here [https://github.com/flashlight/flashlight/tree/main/bindings/python](url)  however is still raises this error while running ```cd bindings/python
python3 setup.py install```

`OS: Lnux 18.04`
I have multiple coda on my system including 
`Cuda 10.0, 10.1, 10.2 and 11.0`

And this is the error raises:

```
running install
running bdist_egg
running egg_info
writing flashlight.egg-info/PKG-INFO
writing dependency_links to flashlight.egg-info/dependency_links.txt
writing top-level names to flashlight.egg-info/top_level.txt
package init file 'flashlight/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/audio/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/sequence/__init__.py' not found (or not a regular file)
reading manifest file 'flashlight.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'flashlight.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
-- -rdynamic supported.
-- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY) (found version "2.2")
-- The CUDA compiler identification is unknown
-- Check for working CUDA compiler: /usr/local/cuda-10.0/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-10.0/bin/nvcc -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/usr/local/cuda-10.0/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/ai-labs-sgoudarzvand/flashlight/bindings/python/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_ac27d/fast"
    /usr/bin/make -f CMakeFiles/cmTC_ac27d.dir/build.make CMakeFiles/cmTC_ac27d.dir/build
    make[1]: Entering directory '/home/ai-labs-sgoudarzvand/flashlight/bindings/python/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_ac27d.dir/main.cu.o
    /usr/local/cuda-10.0/bin/nvcc     -x cu -c /home/ai-labs-sgoudarzvand/flashlight/bindings/python/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_ac27d.dir/main.cu.o
    cc1plus: fatal error: cuda_runtime.h: No such file or directory
    compilation terminated.
    CMakeFiles/cmTC_ac27d.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_ac27d.dir/main.cu.o' failed
    make[1]: *** [CMakeFiles/cmTC_ac27d.dir/main.cu.o] Error 1
    make[1]: Leaving directory '/home/ai-labs-sgoudarzvand/flashlight/bindings/python/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_ac27d/fast' failed
    make: *** [cmTC_ac27d/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:88 (enable_language)


-- Configuring incomplete, errors occurred!
See also "/home/ai-labs-sgoudarzvand/flashlight/bindings/python/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/home/ai-labs-sgoudarzvand/flashlight/bindings/python/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 129, in <module>
    python_requires=">=3.6",
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
    self.build()
  File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 56, in run
    self.build_extensions(ext)
  File "setup.py", line 102, in build_extensions
    ["cmake", source_dir] + cmake_args, cwd=self.build_temp, env=env
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/ai-labs-sgoudarzvand/flashlight', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ai-labs-sgoudarzvand/flashlight/bindings/python/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DFL_BUILD_STANDALONE=OFF', '-DBUILD_SHARED_LIBS=ON', '-DFL_BUILD_CORE=OFF', '-DFL_BUILD_ALL_LIBS=ON', '-DFL_BUILD_EXAMPLES=OFF', '-DFL_BUILD_TESTS=OFF', '-DFL_LIBRARIES_BUILD_FOR_PYTHON=ON', '-DFL_LIBRARIES_USE_CUDA=ON', '-DFL_LIBRARIES_USE_MKL=ON', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```

**Comment by jacobkahn** [comment]
The compiler output says it can't find `cuda_runtime.h`. Do you have that header/the CUDA runtime installed on your system?

**Comment by benam2** [comment]
Hi @jacobkahn, Sorry I did miss your reply. I fixed this but its been 5 days dealing with an error. I really appreciate it if you can have a look at this https://github.com/flashlight/flashlight/issues/1003

**Comment by jacobkahn** [comment]
Associated issue's closed
