### ISSUE TITLE
Mnist.cpp aborts in OneDnnTensor::flatten() because of FL_ONEDNN_TENSOR_UNIMPLEMENTED

### ISSUE THREAD

**Issue by yurivict** [flashlight/flashlight#1091]
### Bug Description
```
403│ Tensor OneDnnTensor::flatten() const {
404├─> FL_ONEDNN_TENSOR_UNIMPLEMENTED;
405│ }
```

```
#1  0x000000080192fa74 in __raise (s=s@entry=6) at /disk-samsung/freebsd-src/lib/libc/gen/raise.c:52
#2  0x00000008019e07b9 in abort () at /disk-samsung/freebsd-src/lib/libc/stdlib/abort.c:67
#3  0x000000080070ee79 in report_failure (err=<optimized out>, thrown_exception=0x854e62e00) at /disk-samsung/freebsd-src/contrib/libcxxrt/exception.cc:714
#4  0x00000008014fc150 in fl::OneDnnTensor::flatten (this=0x857b80200) at /usr/ports/math/flashlight/work/flashlight-0.4.0-16-gafcd364e/flashlight/fl/tensor/backend/onednn/OneDnnTensor.cpp:404
#5  0x000000080151ac98 in fl::Tensor::flatten (this=0x7fffffffd680) at /usr/ports/math/flashlight/work/flashlight-0.4.0-16-gafcd364e/flashlight/fl/tensor/TensorBase.cpp:126
#6  0x000000080156d16b in fl::categoricalCrossEntropy (in=..., targets=..., reduction=fl::ReduceMode::MEAN, ignoreIndex=-1)
    at /usr/ports/math/flashlight/work/flashlight-0.4.0-16-gafcd364e/flashlight/fl/autograd/Functions.cpp:1117
```

### Platform and Hardware
FreeBSD 13.1

#### Additional Context
Revision: afcd364e
onednn-2.5.2

**Comment by deepwilson** [comment]
Is this library still being maintained?
@jacobkahn

**Comment by jacobkahn** [comment]
@deepwilson it is - we're in the process of prioritizing features before starting to work consistently again. We'll post a more comprehensive roadmap in the next several weeks.

**Comment by ktimam** [comment]
Are OneDnn unimplemented functions planned to be handled anytime soon?
