### ISSUE TITLE
CMAKE build error /usr/bin/ld: cannot find -lpthreads 

### ISSUE THREAD

**Issue by AetherPrior** [flashlight/flashlight#585]
### Bug Description
There has  been an error I have received regarding the `stb` and the pthread library

#### Reproduction Steps
Built the repository source using a CPU backend. No additional options specified

### Platform and Hardware
Arch Linux, with no dedicated gpu

#### Additional Context
Output of the CMake command:
```
$ cmake .. -DCMAKE_BUILD_TYPE=Release -DFL_BACKEND=CPU
-- -rdynamic supported.
-- gtest found: (include: , lib: GTest::gtest;GTest::gtest_main
-- Found gtest and gmock on system.
-- Will build flashlight libraries.
-- MKL_THREADING = OMP
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib/libpthread.so
--   Library m: /usr/lib/libm.so
--   Library dl: /usr/lib/libdl.so
-- MKL library found
-- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib/libpthread.so;/usr/lib/libm.so;/usr/lib/libdl.so)
CMake Error at /usr/lib64/cmake/fftw3/FFTW3Config.cmake:13 (include):
  include could not find requested file:

    /usr/lib64/cmake/fftw3/FFTW3LibraryDepends.cmake
Call Stack (most recent call first):
  cmake/FindFFTW3.cmake:22 (find_package)
  flashlight/lib/audio/feature/CMakeLists.txt:17 (find_package)
  flashlight/lib/audio/CMakeLists.txt:6 (include)
  flashlight/lib/CMakeLists.txt:31 (include)
  CMakeLists.txt:133 (include)


-- FFTW found
-- Looking for KenLM
-- Using kenlm library found in /lib/libkenlm.a
-- Using kenlm utils library found in /lib/libkenlm_util.a
-- kenlm model.hh found in /usr/include/kenlm/lm
-- Found kenlm: /usr/include  
-- Found kenlm (include: /usr/include, library: /lib/libkenlm.a;/lib/libkenlm_util.a;/usr/lib/liblzma.so;/usr/lib/libbz2.so;/usr/lib/libz.so)
-- FL_BACKEND is not CUDA - forcing FL_LIBRARIES_USE_CUDA to OFF
-- Will build flashlight core and extensions.
-- ArrayFire found (include: /usr/include, library: ArrayFire::afcuda)
-- Found cereal
-- Will build flashlight contrib assets.
-- Could NOT find Gloo (missing: Gloo_DIR)
-- Gloo not found - downloading and building from source
-- MPI_VERSION found:  3.1
-- MPI_CXX found
-- MPI_CXX compile flags: -pthread
-- MPI_CXX include path: /usr/include
-- MPI_CXX LINK flags path: -Wl,-rpath -Wl,/usr/lib64 -Wl,-rpath -Wl,/usr/lib/openmpi -Wl,--enable-new-dtags -L/usr/lib -pthread
-- MPI_CXX libraries: /usr/lib/openmpi/libmpi_cxx.so/usr/lib/openmpi/libmpi.so
-- MPI_C found
-- MPI_C compile flags: -pthread
-- MPI_C include path: /usr/include
-- MPI_C LINK flags path: -Wl,-rpath -Wl,/usr/lib64 -Wl,-rpath -Wl,/usr/lib/openmpi -Wl,--enable-new-dtags -L/usr/lib -pthread
-- MPI_C libraries: /usr/lib/openmpi/libmpi.so
-- Could NOT find stb (missing: stb_INCLUDE_DIRS) 
-- Could not find stb_image.h. Will download stb from github
-- Configuring incomplete, errors occurred!
See also "/home/cat/Documents/git_clones/flashlight/build/CMakeFiles/CMakeOutput.log".
See also "/home/cat/Documents/git_clones/flashlight/build/CMakeFiles/CMakeError.log".
```
Output of the `CMakeError.log` file:  
```
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/cat/Documents/git_clones/flashlight/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_cb128/fast && /usr/bin/make  -f CMakeFiles/cmTC_cb128.dir/build.make CMakeFiles/cmTC_cb128.dir/build
make[1]: Entering directory '/home/cat/Documents/git_clones/flashlight/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_cb128.dir/src.c.o
/usr/bin/cc -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_cb128.dir/src.c.o -c /home/cat/Documents/git_clones/flashlight/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_cb128
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_cb128.dir/link.txt --verbose=1
/usr/bin/cc  -rdynamic  CMakeFiles/cmTC_cb128.dir/src.c.o -o cmTC_cb128 
/usr/bin/ld: CMakeFiles/cmTC_cb128.dir/src.c.o: in function `main':
src.c:(.text+0x3e): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x4a): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x56): undefined reference to `pthread_cancel'
/usr/bin/ld: src.c:(.text+0x67): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_cb128.dir/build.make:99: cmTC_cb128] Error 1
make[1]: Leaving directory '/home/cat/Documents/git_clones/flashlight/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_cb128/fast] Error 2


Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/cat/Documents/git_clones/flashlight/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_193be/fast && /usr/bin/make  -f CMakeFiles/cmTC_193be.dir/build.make CMakeFiles/cmTC_193be.dir/build
make[1]: Entering directory '/home/cat/Documents/git_clones/flashlight/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_193be.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create -o CMakeFiles/cmTC_193be.dir/CheckFunctionExists.c.o -c /usr/share/cmake-3.20/Modules/CheckFunctionExists.c
Linking C executable cmTC_193be
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_193be.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create  -rdynamic  CMakeFiles/cmTC_193be.dir/CheckFunctionExists.c.o -o cmTC_193be  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_193be.dir/build.make:99: cmTC_193be] Error 1
make[1]: Leaving directory '/home/cat/Documents/git_clones/flashlight/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_193be/fast] Error 2

```

**Comment by malloc-naski** [comment]
Similar issue here when building Flashlight Python Bindings using `python setup.py install`:
### Trace
 ```

running install
running bdist_egg
running egg_info
writing flashlight.egg-info/PKG-INFO
writing dependency_links to flashlight.egg-info/dependency_links.txt
writing top-level names to flashlight.egg-info/top_level.txt
package init file 'flashlight/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/audio/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/sequence/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/text/__init__.py' not found (or not a regular file)
reading manifest file 'flashlight.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'flashlight.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
-- -rdynamic supported.
-- CUDA found (library: /usr/local/cuda-11.1/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda-11.1/include)
-- CUDA architecture flags: -gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_80,code=sm_80-gencodearch=compute_80,code=compute_80
-- Will build flashlight libraries.
-- MKL_THREADING = OMP
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
--   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
-- MKL library found
-- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so)
CMake Error at /usr/local/lib/cmake/fftw3/FFTW3Config.cmake:13 (include):
  include could not find load file:

    /usr/local/lib/cmake/fftw3/FFTW3LibraryDepends.cmake
Call Stack (most recent call first):
  cmake/FindFFTW3.cmake:22 (find_package)
  flashlight/lib/audio/feature/CMakeLists.txt:17 (find_package)
  flashlight/lib/audio/CMakeLists.txt:6 (include)
  flashlight/lib/CMakeLists.txt:31 (include)
  CMakeLists.txt:133 (include)


-- FFTW found
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- Looking for KenLM
-- Using kenlm library found in /home/mallonus/kenlm/build/lib/libkenlm.a
-- Using kenlm utils library found in /home/mallonus/kenlm/build/lib/libkenlm_util.a
-- kenlm model.hh found in /home/mallonus/kenlm/lm
-- Found kenlm (include: /home/mallonus, library: /home/mallonus/kenlm/build/lib/libkenlm.a;/home/mallonus/kenlm/build/lib/libkenlm_util.a;/usr/lib/x86_64-linux-gnu/liblzma.so;/usr/lib/x86_64-linux-gnu/libbz2.so;/usr/lib/x86_64-linux-gnu/libz.so)
-- Configuring incomplete, errors occurred!
See also "/home/mallonus/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
See also "/home/mallonus/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 111, in <module>
    setup(
  File "/home/mallonus/fsq/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/mallonus/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/mallonus/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/mallonus/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/mallonus/fsq/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/mallonus/fsq/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/mallonus/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/mallonus/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/mallonus/fsq/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/mallonus/fsq/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "/home/mallonus/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/mallonus/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/mallonus/fsq/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/mallonus/anaconda3/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/mallonus/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/mallonus/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 56, in run
    self.build_extensions(ext)
  File "setup.py", line 105, in build_extensions
    subprocess.check_call(
  File "/home/mallonus/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/mallonus/flashlight', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/mallonus/flashlight/bindings/python/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/home/mallonus/fsq/bin/python', '-DFL_BUILD_STANDALONE=OFF', '-DBUILD_SHARED_LIBS=ON', '-DFL_BUILD_LIBRARIES=ON', '-DFL_BUILD_CORE=OFF', '-DFL_BUILD_TESTS=OFF', '-DFL_BUILD_EXAMPLES=OFF', '-DFL_BACKEND=CUDA', '-DFL_LIBRARIES_BUILD_FOR_PYTHON=ON', '-DFL_LIBRARIES_USE_CUDA=ON', '-DFL_LIBRARIES_USE_KENLM=ON', '-DFL_LIBRARIES_USE_MKL=ON', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

```
-------------------------------------------------------------------------------------------------------------------------------------------
### CMakeError.log
```
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/mallonus/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_638fc/fast && /usr/bin/make -f CMakeFiles/cmTC_638fc.dir/build.make CMakeFiles/cmTC_638fc.dir/build
make[1]: Entering directory '/home/mallonus/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_638fc.dir/src.c.o
/usr/bin/cc   -fPIC -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_638fc.dir/src.c.o   -c /home/mallonus/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_638fc
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_638fc.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -DCMAKE_HAVE_LIBC_PTHREAD   -rdynamic  CMakeFiles/cmTC_638fc.dir/src.c.o  -o cmTC_638fc
/usr/bin/ld: CMakeFiles/cmTC_638fc.dir/src.c.o: in function `main':
src.c:(.text+0x46): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x52): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x63): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_638fc.dir/build.make:87: cmTC_638fc] Error 1
make[1]: Leaving directory '/home/mallonus/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_638fc/fast] Error 2


Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/mallonus/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_1a9d3/fast && /usr/bin/make -f CMakeFiles/cmTC_1a9d3.dir/build.make CMakeFiles/cmTC_1a9d3.dir/build
make[1]: Entering directory '/home/mallonus/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_1a9d3.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_1a9d3.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.16/Modules/CheckFunctionExists.c
Linking C executable cmTC_1a9d3
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_1a9d3.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -rdynamic  CMakeFiles/cmTC_1a9d3.dir/CheckFunctionExists.c.o  -o cmTC_1a9d3  -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_1a9d3.dir/build.make:87: cmTC_1a9d3] Error 1
make[1]: Leaving directory '/home/mallonus/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_1a9d3/fast] Error 2
```

**Comment by tlikhomanenko** [comment]
Please see solution here https://github.com/flashlight/flashlight/issues/535, let us know if this solves the issue.

**Comment by AetherPrior** [comment]
I tried to reinstall the `fftw` package from `pacman` and the AUR, but neither of them create the `FFTW3LibraryDepends.cmake` file. I'm not very sure what to do :sweat_smile:

**Comment by tlikhomanenko** [comment]
Did you install https://github.com/flashlight/flashlight/blob/master/.docker/Dockerfile-CUDA-Base#L45?

**Comment by jacobkahn** [comment]
@AetherPrior you're missing libpthread (or an acceptable alternative) on your machine, as the error indicates. Hard to know why, but your compiler's `libc` might be missing symbols. You can try installing a different compiler version or the arch package - https://aur.archlinux.org/packages/libpthread-stubs/

**Comment by AetherPrior** [comment]
@tlikhomanenko the package `libfftw3-dev` is the `fftw` package in arch, and I have it installed.  
@jacobkahn the pthread library is installed, and correct me if I'm wrong, the flag used for the compilation is normally `-lpthread` right? The makefile shows `-lpthreads`.  
Thanks!

**Comment by malloc-naski** [comment]
I solved the problem thanks to [this issue](https://github.com/FFTW/fftw3/issues/130) regarding the FFTW3 missing file and now the installation works just fine, hope this helps @AetherPrior 

```
mkdir build
cd build
cmake ..
make -j 4
sudo make install
sudo cp FFTW3LibraryDepends.cmake /usr/local/lib/cmake/fftw3/
```
