### ISSUE TITLE
error in installing bindings

### ISSUE THREAD

**Issue by liu-x-p** [flashlight/flashlight#598]
Hi, I'm useing the fairseq ASR-testing, and I need the bindings package in this work.
I have installed the dependencies and run the command ` python3 setup.py install`, but it threw errors.

```
running install
running bdist_egg
running egg_info
writing flashlight.egg-info/PKG-INFO
writing dependency_links to flashlight.egg-info/dependency_links.txt
writing top-level names to flashlight.egg-info/top_level.txt
package init file 'flashlight/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/audio/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/sequence/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/text/__init__.py' not found (or not a regular file)
reading manifest file 'flashlight.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'flashlight.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
-- -rdynamic supported.
-- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
-- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_75,code=compute_75
-- Will build flashlight libraries.
-- MKL_THREADING = OMP
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
--   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
-- MKL library found
-- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so)
-- FFTW found
-- Looking for KenLM
-- Using kenlm library found in /home/speech/kenlm-master/lib/libkenlm.a
-- Using kenlm utils library found in /home/speech/kenlm-master/lib/libkenlm_util.a
-- kenlm model.hh found in /home/speech/kenlm-master/lm
-- Found kenlm (include: /home/speech, library: /home/speech/kenlm-master/lib/libkenlm.a;/home/speech/kenlm-master/lib/libkenlm_util.a;/usr/lib/x86_64-linux-gnu/liblzma.so;/usr/lib/x86_64-linux-gnu/libbz2.so;/usr/lib/x86_64-linux-gnu/libz.so)
-- Could NOT find cub (missing: cub_INCLUDE_DIRS) 
-- Could not find cub - will download from source
-- Configuring done
-- Generating done
-- Build files have been written to: /home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7
[  1%] Performing update step for 'pybind11'
[  3%] Performing update step for 'CUB'
[  4%] No configure step for 'CUB'
[  6%] No configure step for 'pybind11'
[  8%] No build step for 'CUB'
[  9%] No build step for 'pybind11'
[ 11%] No install step for 'CUB'
[ 13%] No install step for 'pybind11'
[ 14%] Completed 'CUB'
[ 16%] Completed 'pybind11'
[ 21%] Built target pybind11
[ 26%] Built target CUB
[ 86%] Built target fl-libraries
[ 90%] Built target flashlight_lib_text_decoder
[ 93%] Built target flashlight_lib_audio_feature
[ 96%] Built target flashlight_lib_text_dictionary
[ 98%] Building CXX object CMakeFiles/flashlight_lib_sequence_criterion.dir/bindings/python/flashlight/lib/sequence/_criterion.cpp.o
In file included from /home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/specializations/../../block/../util_ptx.cuh:37:0,
                 from /home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/specializations/../../block/block_exchange.cuh:36,
                 from /home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/specializations/../../block/block_radix_sort.cuh:37,
                 from /home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/specializations/block_histogram_sort.cuh:36,
                 from /home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/block_histogram.cuh:36,
                 from /home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/cub.cuh:38,
                 from /home/speech/flashlight-master/bindings/python/flashlight/lib/sequence/_criterion.cpp:9:
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/specializations/../../block/../util_type.cuh:261:5: error: ‘__host__’ does not name a type; did you mean ‘__lxstat’?
     __host__ __device__ __forceinline__ NullType& operator =(const T&) { return *this; }
     ^~~~~~~~
     __lxstat
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/specializations/../../block/../util_type.cuh:263:5: error: ‘__host__’ does not name a type; did you mean ‘__lxstat’?
     __host__ __device__ __forceinline__ bool operator ==(const NullType&) { return true; }
     ^~~~~~~~
     __lxstat
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/specializations/../../block/../util_type.cuh:265:5: error: ‘__host__’ does not name a type; did you mean ‘__lxstat’?
     __host__ __device__ __forceinline__ bool operator !=(const NullType&) { return false; }
     ^~~~~~~~
     __lxstat
In file included from /home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/specializations/../../block/../util_ptx.cuh:37:0,
                 from /home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/specializations/../../block/block_exchange.cuh:36,
                 from /home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/specializations/../../block/block_radix_sort.cuh:37,
                 from /home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/specializations/block_histogram_sort.cuh:36,
                 from /home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/block_histogram.cuh:36,
                 from /home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/cub.cuh:38,
                 from /home/speech/flashlight-master/bindings/python/flashlight/lib/sequence/_criterion.cpp:9:
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/specializations/../../block/../util_type.cuh:316:19: error: ‘short4’ was not declared in this scope
 __CUB_ALIGN_BYTES(short4, 8)
                   ^
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/specializations/../../block/../util_type.cuh:313:35: note: in definition of macro ‘__CUB_ALIGN_BYTES’
     template <> struct AlignBytes<t>    \
                                   ^
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/block/specializations/../../block/../util_type.cuh:316:19: note: suggested alternative: ‘short’
 __CUB_ALIGN_BYTES(short4, 8)
                   ^
```

......

```
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/iterator/tex_obj_input_iterator.cuh:286:25: error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__ bool operator==(const self_type& rhs)
                         ^~~~~~~~~~~~~~~
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/iterator/tex_obj_input_iterator.cuh:292:25: error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__ bool operator!=(const self_type& rhs)
                         ^~~~~~~~~~~~~~~
In file included from /home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/cub.cuh:86:0,
                 from /home/speech/flashlight-master/bindings/python/flashlight/lib/sequence/_criterion.cpp:9:
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/iterator/transform_input_iterator.cuh:148:25: error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__ TransformInputIterator(
                         ^~~~~~~~~~~~~~~
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/iterator/transform_input_iterator.cuh:157:25: error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__ self_type operator++(int)
                         ^~~~~~~~~~~~~~~
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/iterator/transform_input_iterator.cuh:165:25: error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__ self_type operator++()
                         ^~~~~~~~~~~~~~~
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/iterator/transform_input_iterator.cuh:172:25: error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__ reference operator*() const
                         ^~~~~~~~~~~~~~~
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/iterator/transform_input_iterator.cuh:179:25: error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__ self_type operator+(Distance n) const
                         ^~~~~~~~~~~~~~~
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/iterator/transform_input_iterator.cuh:187:25: error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__ self_type& operator+=(Distance n)
                         ^~~~~~~~~~~~~~~
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/iterator/transform_input_iterator.cuh:195:25: error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__ self_type operator-(Distance n) const
                         ^~~~~~~~~~~~~~~
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/iterator/transform_input_iterator.cuh:203:25: error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__ self_type& operator-=(Distance n)
                         ^~~~~~~~~~~~~~~
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/iterator/transform_input_iterator.cuh:210:25: error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__ difference_type operator-(self_type other) const
                         ^~~~~~~~~~~~~~~
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/iterator/transform_input_iterator.cuh:217:25: error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__ reference operator[](Distance n) const
                         ^~~~~~~~~~~~~~~
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/iterator/transform_input_iterator.cuh:223:25: error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__ pointer operator->()
                         ^~~~~~~~~~~~~~~
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/iterator/transform_input_iterator.cuh:229:25: error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__ bool operator==(const self_type& rhs)
                         ^~~~~~~~~~~~~~~
/home/speech/flashlight-master/bindings/python/build/temp.linux-x86_64-3.7/CUB/src/CUB/cub/iterator/transform_input_iterator.cuh:235:25: error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__ bool operator!=(const self_type& rhs)
                         ^~~~~~~~~~~~~~~
CMakeFiles/flashlight_lib_sequence_criterion.dir/build.make:62: recipe for target 'CMakeFiles/flashlight_lib_sequence_criterion.dir/bindings/python/flashlight/lib/sequence/_criterion.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight_lib_sequence_criterion.dir/bindings/python/flashlight/lib/sequence/_criterion.cpp.o] Error 1
CMakeFiles/Makefile2:1028: recipe for target 'CMakeFiles/flashlight_lib_sequence_criterion.dir/all' failed
make[1]: *** [CMakeFiles/flashlight_lib_sequence_criterion.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 134, in <module>
    python_requires=">=3.6",
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 56, in run
    self.build_extensions(ext)
  File "setup.py", line 109, in build_extensions
    ["cmake", "--build", "."] + build_args, cwd=self.build_temp
  File "/home/speech/anaconda3/envs/end2end/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

```
There are all this kind of errors, do you have any ideas of it?
Thank you.

**Comment by liu-x-p** [comment]
The CUDA version is 10.2, Python version is 3.7. The package cub-1.8 and pybind11 are download during the compilation.

**Comment by liu-x-p** [comment]
[error.txt](https://github.com/flashlight/flashlight/files/6462691/error.txt)
This is the full error from the command `python3 setup.py install`

**Comment by tlikhomanenko** [comment]
@jacobkahn any idea on the CUB version mismatch with cuda 10.2?

**Comment by jacobkahn** [comment]
@liu-x-p — what's your OS/compiler version?

**Comment by liu-x-p** [comment]
@jacobkahn
OS: Ubuntu 18.04.5 LTS
GPU: GeForce GTX 1080 Ti
CUDA Version: 10.2
Python Version: 3.7.0
Torch Version: 1.6.0
GCC: 7.5.0
cmake: 3.15.6

**Comment by liu-x-p** [comment]
I deleted all files about flashlight and tried to install bindings again, this time it worked. I think some error when I installed flashlight caused this problem.
