### ISSUE TITLE
Unable to install python bindings using python3 setup.py install command

### ISSUE THREAD

**Issue by PeiyuChen1005** [flashlight/flashlight#643]
### Question

I failed to install the python bindings using command provided in https://github.com/flashlight/flashlight/tree/master/bindings/python#installation.
Here is the log file I get:
```
running install
running bdist_egg
running egg_info
writing flashlight.egg-info/PKG-INFO
writing dependency_links to flashlight.egg-info/dependency_links.txt
writing top-level names to flashlight.egg-info/top_level.txt
package init file 'flashlight/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/audio/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/sequence/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/text/__init__.py' not found (or not a regular file)
reading manifest file 'flashlight.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'flashlight.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
-- -rdynamic supported.
-- Will build flashlight libraries.
libraries criterions are not implemented for non-CUDA backends
-- MKL_THREADING = OMP
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /home/pychen/intel/oneapi/mkl/latest/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /home/pychen/intel/oneapi/mkl/latest/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /home/pychen/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
--   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
-- MKL library found
-- CBLAS found (include: /home/pychen/intel/oneapi/mkl/latest/include, library: /home/pychen/intel/oneapi/mkl/latest/lib/intel64/libmkl_intel_lp64.so;/home/pychen/intel/oneapi/mkl/latest/lib/intel64/libmkl_gnu_thread.so;/home/pychen/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so)
-- Could NOT find FFTW3 (missing: FFTW3_DIR)
-- FindFFTW using pkgconfig: FOUND=1 LIBRARIES=fftw3 LIBRARY_DIRS= LIBDIR=/usr/lib/x86_64-linux-gnu LINK_LIBRARIES=
-- FindFTTW using pkgconfig: INCLUDE_DIRS= INCLUDEDIR=/usr/include
-- FFTW found
-- Looking for KenLM
-- kenlm library not found; if you already have kenlm installed, please set CMAKE_LIBRARY_PATH, KENLM_LIB or KENLM_ROOT environment variable
-- kenlm utils library not found; if you already have kenlm installed, please set CMAKE_LIBRARY_PATH, KENLM_UTIL_LIB or KENLM_ROOT environment variable
-- kenlm model.hh found in /home/pychen/kenlm/include/lm
-- Found kenlm: /home/pychen/kenlm  
-- Found kenlm (include: /home/pychen/kenlm, library: KENLM_LIB-NOTFOUND;KENLM_UTIL_LIB-NOTFOUND;/usr/lib/x86_64-linux-gnu/liblzma.so;/usr/lib/x86_64-linux-gnu/libbz2.so;/usr/lib/x86_64-linux-gnu/libz.so)-- FL_BACKEND is not CUDA - forcing FL_LIBRARIES_USE_CUDA to OFF
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
KENLM_LIB
    linked by target "fl-libraries" in directory /home/pychen/flashlight
KENLM_UTIL_LIB
    linked by target "fl-libraries" in directory /home/pychen/flashlight

-- Configuring incomplete, errors occurred!
See also "/home/pychen/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
See also "/home/pychen/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 111, in <module>
    setup(
  File "/home/pychen/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/pychen/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/pychen/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/pychen/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pychen/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/pychen/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/pychen/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/pychen/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pychen/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/pychen/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/home/pychen/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/pychen/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pychen/anaconda3/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/pychen/anaconda3/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/pychen/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/pychen/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 56, in run
    self.build_extensions(ext)
  File "setup.py", line 105, in build_extensions
    subprocess.check_call(
  File "/home/pychen/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/pychen/flashlight', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/pychen/flashlight/bindings/python/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/home/pychen/anaconda3/bin/python3', '-DFL_BUILD_STANDALONE=OFF', '-DBUILD_SHARED_LIBS=ON', '-DFL_BUILD_LIBRARIES=ON', '-DFL_BUILD_CORE=OFF', '-DFL_BUILD_TESTS=OFF', '-DFL_BUILD_EXAMPLES=OFF', '-DFL_BACKEND=CPU', '-DFL_LIBRARIES_BUILD_FOR_PYTHON=ON', '-DFL_LIBRARIES_USE_CUDA=OFF', '-DFL_LIBRARIES_USE_KENLM=ON', '-DFL_LIBRARIES_USE_MKL=ON', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

```
I have 2 questions:
 * I do have a CUDA DEVICE but the setip.py seems failed to detect that, how can I install CUDA backend python bindings correctly?
 *  I've followed issue #462 , add a `export KENLM_ROOT=/home/pychen/kenlm/include` line to my ~/.bashrc file ,but still get this  log output, how can I fix that?
 
#### Additional Context
Any help is appreciated. :)

**Comment by seungjungjin-pf** [comment]
same problem -- the setup gives a sequence of path error -> fix path -> new path error. I'm still wrestling to get the code to work

**Comment by harveenchadha** [comment]
Kenlm Root should be 

KENLM_ROOT=/home/pychen/kenlm

Can you please check?

**Comment by harveenchadha** [comment]
Sorry, compiling on CUDA is a bit complicated as you need to have CUDA 10 for this to work. I would advice you to try install without CUDA first and see if it works.


```
git clone https://github.com/kpu/kenlm.git
cd kenlm
mkdir -p build && cd build
cmake .. 
make -j 16
cd ..
export KENLM_ROOT=$PWD
export USE_CUDA=0 ## for cpu
cd ..


git clone https://github.com/flashlight/flashlight.git
cd flashlight/bindings/python
export USE_MKL=0
python setup.py install
```

**Comment by PeiyuChen1005** [comment]
> Sorry, compiling on CUDA is a bit complicated as you need to have CUDA 10 for this to work. I would advice you to try install without CUDA first and see if it works.
> 
> ```
> git clone https://github.com/kpu/kenlm.git
> cd kenlm
> mkdir -p build && cd build
> cmake .. 
> make -j 16
> cd ..
> export KENLM_ROOT=$PWD
> export USE_CUDA=0 ## for cpu
> cd ..
> 
> 
> git clone https://github.com/flashlight/flashlight.git
> cd flashlight/bindings/python
> export USE_MKL=0
> python setup.py install
> ```

Thank you!My CUDA version is CUDA11.2, and I can't change my CUDA version due to the I am not a sudo user of the server I'm using. So is it a strict constrain that the CUDA version should be 10?

**Comment by tlikhomanenko** [comment]
You can use 11.2 too. Could you post exact error on CUDA which you see?

**Comment by PeiyuChen1005** [comment]
> You can use 11.2 too. Could you post exact error on CUDA which you see?
Here is the error log:
```
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC - Success
-- -rdynamic supported.
-- The CUDA compiler identification is NVIDIA 11.2.152
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
CMake Error at cmake/CUDAUtils.cmake:12 (message):
  CUDA required to build CUDA backend
Call Stack (most recent call first):
  CMakeLists.txt:100 (include)


-- Configuring incomplete, errors occurred!
See also "/home/pychen/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 111, in <module>
    setup(
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 56, in run
    self.build_extensions(ext)
  File "setup.py", line 105, in build_extensions
    subprocess.check_call(
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/pychen/flashlight', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/pychen/flashlight/bindings/python/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/home/pychen/anaconda3/envs/fairseq/bin/python3', '-DFL_BUILD_STANDALONE=OFF', '-DBUILD_SHARED_LIBS=ON', '-DFL_BUILD_LIBRARIES=ON', '-DFL_BUILD_CORE=OFF', '-DFL_BUILD_TESTS=OFF', '-DFL_BUILD_EXAMPLES=OFF', '-DFL_BACKEND=CUDA', '-DFL_LIBRARIES_BUILD_FOR_PYTHON=ON', '-DFL_LIBRARIES_USE_CUDA=ON', '-DFL_LIBRARIES_USE_KENLM=ON', '-DFL_LIBRARIES_USE_MKL=ON', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```
Thanks for your reply~~~

**Comment by PeiyuChen1005** [comment]
I've finished install this binding, thanks for all your help!!!
And I'm going to close this issues now, but feel free to reopen this if someone else facing the same problem someday~

**Comment by seungjungjin-pf** [comment]
> I've finished install this binding, thanks for all your help!!!
> And I'm going to close this issues now, but feel free to reopen this if someone else facing the same problem someday~

How did you handle the CUDA error? My system has CUDA but the make script can't locate it

**Comment by PeiyuChen1005** [comment]
> > I've finished install this binding, thanks for all your help!!!
> > And I'm going to close this issues now, but feel free to reopen this if someone else facing the same problem someday~
> 
> How did you handle the CUDA error? My system has CUDA but the make script can't locate it

Please check your cuda install location first. 
Take my case as an example, I'm using a server and the cuda install location is `/usr/local/cuda-11.2`. 
First I add these to my `~/.bashrc`:
```
export PATH="/usr/local/cuda-11.2/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda-11.2/lib64:$LD_LIBRARY_PATH"
```
and run `source ~/.bashrc`.
Then `cd flashlight/bindings/python` and `rm -rf build` then run `python3 setup.py install`.
This may help you handle your problem~

**Comment by harveenchadha** [comment]
@PeiyuChen1005 How do you check if flashlight is actually using CUDA or CPU for your process?

**Comment by PeiyuChen1005** [comment]
> @PeiyuChen1005 How do you check if flashlight is actually using CUDA or CPU for your process?

I haven't verified this problem yet. But maybe the log printed when run `python3 setup.py install` command proved this a little? I'll check which backend flashlight really use and reply to you asap.

**Comment by tlikhomanenko** [comment]
See default settings here https://github.com/flashlight/flashlight/blob/master/bindings/python/setup.py#L20-L24 - CUDA is enabled by default, so if you didn't reset flags it will install CUDA version
