### ISSUE TITLE
Build error while installing through pip

### ISSUE THREAD

**Issue by harveenchadha** [flashlight/flashlight#655]
Hi,

I am trying to get flashlight working through pip as I am creating a library that is dependent on this build.

I install kenlm using:

`pip install pypi-kenlm`

Kenlm is working and tested but when I install flashlight, there is some problem. Kenlm is still found but it looks like flashlight need the uncompiled files

```
 pip install git+https://github.com/harveenchadha/flashlight.git#subdirectory=bindings/python
Collecting git+https://github.com/harveenchadha/flashlight.git#subdirectory=bindings/python
  Cloning https://github.com/harveenchadha/flashlight.git to /tmp/pip-req-build-630_rirb
  Running command git clone -q https://github.com/harveenchadha/flashlight.git /tmp/pip-req-build-630_rirb
Building wheels for collected packages: flashlight
  Building wheel for flashlight (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/envs/test/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-630_rirb/bindings/python/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-630_rirb/bindings/python/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-qjk5pvxq
       cwd: /tmp/pip-req-build-630_rirb/bindings/python
  Complete output (208 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'flashlight/__init__.py' not found (or not a regular file)
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/flashlight
  creating build/lib.linux-x86_64-3.7/flashlight/lib
  copying flashlight/lib/__init__.py -> build/lib.linux-x86_64-3.7/flashlight/lib
  package init file 'flashlight/lib/audio/__init__.py' not found (or not a regular file)
  creating build/lib.linux-x86_64-3.7/flashlight/lib/audio
  copying flashlight/lib/audio/feature.py -> build/lib.linux-x86_64-3.7/flashlight/lib/audio
  package init file 'flashlight/lib/sequence/__init__.py' not found (or not a regular file)
  creating build/lib.linux-x86_64-3.7/flashlight/lib/sequence
  copying flashlight/lib/sequence/criterion.py -> build/lib.linux-x86_64-3.7/flashlight/lib/sequence
  copying flashlight/lib/sequence/criterion_torch.py -> build/lib.linux-x86_64-3.7/flashlight/lib/sequence
  package init file 'flashlight/lib/text/__init__.py' not found (or not a regular file)
  creating build/lib.linux-x86_64-3.7/flashlight/lib/text
  copying flashlight/lib/text/decoder.py -> build/lib.linux-x86_64-3.7/flashlight/lib/text
  copying flashlight/lib/text/dictionary.py -> build/lib.linux-x86_64-3.7/flashlight/lib/text
  running build_ext
  -- The CXX compiler identification is GNU 8.3.0
  -- The C compiler identification is GNU 8.3.0
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Performing Test COMPILER_SUPPORTS_RDYNAMIC
  -- Performing Test COMPILER_SUPPORTS_RDYNAMIC - Success
  -- -rdynamic supported.
  -- The CUDA compiler identification is NVIDIA 11.0.194
  -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
  -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
  -- Detecting CUDA compiler ABI info
  -- Detecting CUDA compiler ABI info - done
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - not found
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  -- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
  -- CUDA architecture flags: -gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_80,code=sm_80
  -- Will build flashlight libraries.
  -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29")
  -- Checking for module 'cblas'
  --   No package 'cblas' found
  -- Looking for sys/types.h
  -- Looking for sys/types.h - found
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for stddef.h
  -- Looking for stddef.h - found
  -- Check size of void*
  -- Check size of void* - done
  -- Checking for [Accelerate]
  -- Checking for [vecLib]
  -- Checking for [cblas - atlas]
  -- Includes found
  -- Checking for [openblas]
  -- Includes found
  -- Looking for cblas_dgemm
  -- Looking for cblas_dgemm - found
  -- CBLAS Symbols FOUND
  -- CBLAS library found
  -- CBLAS found (include: /usr/include/x86_64-linux-gnu, library: /usr/lib/x86_64-linux-gnu/libopenblas.so)
  -- Could NOT find FFTW3 (missing: FFTW3_DIR)
  -- FindFFTW using pkgconfig: FOUND=1 LIBRARIES=fftw3 LIBRARY_DIRS= LIBDIR=/usr/lib/x86_64-linux-gnu LINK_LIBRARIES=/usr/lib/x86_64-linux-gnu/libfftw3.so
  -- FindFTTW using pkgconfig: INCLUDE_DIRS= INCLUDEDIR=/usr/include
  -- Found FFTW3: /usr/include
  -- FFTW found
  -- Found OpenMP_C: -fopenmp (found version "4.5")
  -- Found OpenMP_CXX: -fopenmp (found version "4.5")
  -- Found OpenMP: TRUE (found version "4.5")
  -- Looking for KenLM
  -- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so
  -- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
  -- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so
  -- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
  -- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so
  -- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
  -- Found LibLZMA: /usr/include (found version "5.2.4")
  -- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6")
  -- Looking for BZ2_bzCompressInit
  -- Looking for BZ2_bzCompressInit - found
  -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
  -- Using kenlm library found in /opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info
  -- Using kenlm utils library found in /opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info
  -- kenlm model.hh found in /opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info
  -- Found kenlm: /opt/conda/envs/fairseq2/lib/python3.7
  -- Found kenlm (include: /opt/conda/envs/fairseq2/lib/python3.7, library: /opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info;/opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info;/usr/lib/x86_64-linux-gnu/liblzma.so;/usr/lib/x86_64-linux-gnu/libbz2.so;/usr/lib/x86_64-linux-gnu/libz.so)
  -- Found PythonInterp: /opt/conda/envs/test/bin/python3.7 (found version "3.7.10")
  -- Found PythonLibs: /opt/conda/envs/test/lib/libpython3.7m.so
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- LTO enabled
  -- Configuring done
  WARNING: Target "fl-libraries" requests linking to directory "/opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info".  Targets may link only to libraries.  CMake is dropping the item.
  WARNING: Target "fl-libraries" requests linking to directory "/opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info".  Targets may link only to libraries.  CMake is dropping the item.
  WARNING: Target "fl-libraries" requests linking to directory "/opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info".  Targets may link only to libraries.  CMake is dropping the item.
  WARNING: Target "fl-libraries" requests linking to directory "/opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info".  Targets may link only to libraries.  CMake is dropping the item.
  -- Generating done
  CMake Warning:
    Manually-specified variables were not used by the project:
  
      KENLM_INC
  
  
  -- Build files have been written to: /tmp/pip-req-build-630_rirb/bindings/python/build/temp.linux-x86_64-3.7
  Scanning dependencies of target pybind11
  [  1%] Creating directories for 'pybind11'
  Scanning dependencies of target fl-libraries
  [  3%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/CriterionUtils.cpp.o
  [  7%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ForceAlignmentCriterion.cpp.o
  [  7%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/set/Hungarian.cpp.o
  [  9%] Performing download step (git clone) for 'pybind11'
  Cloning into 'pybind11'...
  [ 11%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ConnectionistTemporalClassificationCriterion.cpp.o
  [ 12%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/FullConnectionCriterion.cpp.o
  [ 14%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ViterbiPath.cpp.o
  [ 16%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Ceplifter.cpp.o
  [ 18%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Dct.cpp.o
  [ 20%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Derivatives.cpp.o
  [ 22%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Dither.cpp.o
  [ 24%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Mfcc.cpp.o
  [ 25%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Mfsc.cpp.o
  Note: checking out '9a19306fbf30642ca331d0ec88e7da54a96860f9'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by performing another checkout.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -b with the checkout command again. Example:
  
    git checkout -b <new-branch-name>
  
  HEAD is now at 9a19306 bump version to 2.2.4
  Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'tools/clang'
  Cloning into '/tmp/pip-req-build-630_rirb/bindings/python/build/temp.linux-x86_64-3.7/pybind11/src/pybind11/tools/clang'...
  [ 27%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/PowerSpectrum.cpp.o
  [ 29%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/PreEmphasis.cpp.o
  Submodule path 'tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
  [ 31%] No patch step for 'pybind11'
  [ 35%] Performing update step for 'pybind11'
  [ 35%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/SpeechUtils.cpp.o
  [ 37%] No configure step for 'pybind11'
  [ 38%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/TriFilterbank.cpp.o
  [ 40%] No build step for 'pybind11'
  [ 42%] No install step for 'pybind11'
  [ 44%] Completed 'pybind11'
  [ 44%] Built target pybind11
  [ 46%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Windowing.cpp.o
  [ 48%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/common/String.cpp.o
  [ 50%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/common/System.cpp.o
  [ 51%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/ConvLM.cpp.o
  [ 53%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/ZeroLM.cpp.o
  [ 55%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/KenLM.cpp.o
  /tmp/pip-req-build-630_rirb/flashlight/lib/text/decoder/lm/KenLM.cpp:12:10: fatal error: kenlm/lm/model.hh: No such file or directory
   #include <kenlm/lm/model.hh>
            ^~~~~~~~~~~~~~~~~~~
  compilation terminated.
  make[2]: *** [CMakeFiles/fl-libraries.dir/build.make:336: CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/KenLM.cpp.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  make[1]: *** [CMakeFiles/Makefile2:879: CMakeFiles/fl-libraries.dir/all] Error 2
  make: *** [Makefile:141: all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-630_rirb/bindings/python/setup.py", line 141, in <module>
      python_requires=">=3.6",
    File "/opt/conda/envs/test/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "/opt/conda/envs/test/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/conda/envs/test/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/conda/envs/test/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/conda/envs/test/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/opt/conda/envs/test/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/envs/test/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/conda/envs/test/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/conda/envs/test/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/envs/test/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-630_rirb/bindings/python/setup.py", line 56, in run
      self.build_extensions(ext)
    File "/tmp/pip-req-build-630_rirb/bindings/python/setup.py", line 116, in build_extensions
      ["cmake", "--build", "."] + build_args, cwd=self.build_temp
    File "/opt/conda/envs/test/lib/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for flashlight
  Running setup.py clean for flashlight
Failed to build flashlight
Installing collected packages: flashlight
    Running setup.py install for flashlight ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/envs/test/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-630_rirb/bindings/python/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-630_rirb/bindings/python/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dvbfwar7/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/envs/test/include/python3.7m/flashlight
         cwd: /tmp/pip-req-build-630_rirb/bindings/python
    Complete output (92 lines):
    running install
    running build
    running build_py
    package init file 'flashlight/__init__.py' not found (or not a regular file)
    package init file 'flashlight/lib/audio/__init__.py' not found (or not a regular file)
    package init file 'flashlight/lib/sequence/__init__.py' not found (or not a regular file)
    package init file 'flashlight/lib/text/__init__.py' not found (or not a regular file)
    running build_ext
    -- -rdynamic supported.
    -- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
    -- CUDA architecture flags: -gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_80,code=sm_80
    -- Will build flashlight libraries.
    -- Checking for module 'cblas'
    --   No package 'cblas' found
    -- Checking for [Accelerate]
    -- Checking for [vecLib]
    -- Checking for [cblas - atlas]
    -- Includes found
    -- Checking for [openblas]
    -- Includes found
    -- CBLAS Symbols FOUND
    -- CBLAS library found
    -- CBLAS found (include: /usr/include/x86_64-linux-gnu, library: /usr/lib/x86_64-linux-gnu/libopenblas.so)
    -- Could NOT find FFTW3 (missing: FFTW3_DIR)
    -- FindFFTW using pkgconfig: FOUND=1 LIBRARIES=fftw3 LIBRARY_DIRS= LIBDIR=/usr/lib/x86_64-linux-gnu LINK_LIBRARIES=/usr/lib/x86_64-linux-gnu/libfftw3.so
    -- FindFTTW using pkgconfig: INCLUDE_DIRS= INCLUDEDIR=/usr/include
    -- FFTW found
    -- Found OpenMP_C: -fopenmp
    -- Found OpenMP_CXX: -fopenmp
    -- Found OpenMP: TRUE
    -- Looking for KenLM
    -- Using kenlm library found in /opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info
    -- Using kenlm utils library found in /opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info
    -- kenlm model.hh found in /opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info
    -- Found kenlm (include: /opt/conda/envs/fairseq2/lib/python3.7, library: /opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info;/opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info;/usr/lib/x86_64-linux-gnu/liblzma.so;/usr/lib/x86_64-linux-gnu/libbz2.so;/usr/lib/x86_64-linux-gnu/libz.so)
    -- Configuring done
    WARNING: Target "fl-libraries" requests linking to directory "/opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info".  Targets may link only to libraries.  CMake is dropping the item.
    WARNING: Target "fl-libraries" requests linking to directory "/opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info".  Targets may link only to libraries.  CMake is dropping the item.
    WARNING: Target "fl-libraries" requests linking to directory "/opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info".  Targets may link only to libraries.  CMake is dropping the item.
    WARNING: Target "fl-libraries" requests linking to directory "/opt/conda/envs/fairseq2/lib/python3.7/site-packages/kenlm-0.0.0.dist-info".  Targets may link only to libraries.  CMake is dropping the item.
    -- Generating done
    -- Build files have been written to: /tmp/pip-req-build-630_rirb/bindings/python/build/temp.linux-x86_64-3.7
    [  1%] Performing update step for 'pybind11'
    [  3%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/KenLM.cpp.o
    [  7%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconFreeDecoder.cpp.o
    [  7%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconDecoder.cpp.o
    [  9%] No configure step for 'pybind11'
    /tmp/pip-req-build-630_rirb/flashlight/lib/text/decoder/lm/KenLM.cpp:12:10: fatal error: kenlm/lm/model.hh: No such file or directory
     #include <kenlm/lm/model.hh>
              ^~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make[2]: *** [CMakeFiles/fl-libraries.dir/build.make:336: CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/KenLM.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    [ 11%] No build step for 'pybind11'
    [ 12%] No install step for 'pybind11'
    [ 14%] Completed 'pybind11'
    [ 20%] Built target pybind11
    make[1]: *** [CMakeFiles/Makefile2:879: CMakeFiles/fl-libraries.dir/all] Error 2
    make: *** [Makefile:141: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-630_rirb/bindings/python/setup.py", line 141, in <module>
        python_requires=">=3.6",
      File "/opt/conda/envs/test/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/envs/test/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/envs/test/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/conda/envs/test/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/envs/test/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/conda/envs/test/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/opt/conda/envs/test/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/envs/test/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/envs/test/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/opt/conda/envs/test/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/envs/test/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-630_rirb/bindings/python/setup.py", line 56, in run
        self.build_extensions(ext)
      File "/tmp/pip-req-build-630_rirb/bindings/python/setup.py", line 116, in build_extensions
        ["cmake", "--build", "."] + build_args, cwd=self.build_temp
      File "/opt/conda/envs/test/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/envs/test/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-630_rirb/bindings/python/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-630_rirb/bindings/python/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dvbfwar7/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/envs/test/include/python3.7m/flashlight Check the logs for full command output.
```

**Comment by harveenchadha** [comment]
I was able to add kenlm folder to flashlight and change paths to solve this issue. 

Now flashlight is getting intalled using pip but when running I am encountering this issue:

```
python
Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from flashlight.lib.text.dictionary import create_word_dict, load_words
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/test/lib/python3.7/site-packages/flashlight/lib/text/dictionary.py", line 9, in <module>
    from .flashlight_lib_text_dictionary import (
ImportError: libfl-libraries.so.0: cannot open shared object file: No such file or directory

```

**Comment by harveenchadha** [comment]
I have figured out that 
libaries are getting installed but not in a single package under one folder flashlight but across different folders. What can be a solution to this?


```
/opt/conda/envs/test/lib/python3.7/site-packages/flashlight-1.0.0.dist-info/*
/opt/conda/envs/test/lib/python3.7/site-packages/flashlight/lib/*
/opt/conda/envs/test/lib/python3.7/site-packages/libfl-libraries.so
/opt/conda/envs/test/lib/python3.7/site-packages/libfl-libraries.so.0
/opt/conda/envs/test/lib/python3.7/site-packages/libfl-libraries.so.0.3

```

**Comment by harveenchadha** [comment]
@tlikhomanenko Can you please suggest something I should try here?

**Comment by tlikhomanenko** [comment]
Could you try first to install via `pip install -e .` and trying to add the dir into sys.path and see if it works?

Next I would try to build kenlm from source and not doing any changes into our setup.py/flashlight source code. (Here you need to provide KENLM_ROOT path to kenlm folder where build is located).
