### ISSUE TITLE
can not install flashlight via command "python3 setup.py install" -  nvcc fatal   : Unknown option '-fopenmp'

### ISSUE THREAD

**Issue by lizezheng** [flashlight/flashlight#738]
#### ERROR message ####
[ 85%] Linking CUDA device code CMakeFiles/fl-libraries.dir/cmake_device_link.o
nvcc fatal   : Unknown option '-fopenmp'

running install
running bdist_egg
running egg_info
writing flashlight.egg-info/PKG-INFO
writing dependency_links to flashlight.egg-info/dependency_links.txt
writing top-level names to flashlight.egg-info/top_level.txt
package init file 'flashlight/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/audio/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/sequence/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/text/__init__.py' not found (or not a regular file)
reading manifest file 'flashlight.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'flashlight.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
-- -rdynamic supported.
-- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib64/librt.so include: /usr/local/cuda/include)
-- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_75,code=compute_75
-- Will build flashlight libraries.
-- MKL_THREADING = OMP
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib64/libpthread.so
--   Library m: /usr/lib64/libm.so
--   Library dl: /usr/lib64/libdl.so
-- MKL library found
-- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib64/libpthread.so;/usr/lib64/libm.so;/usr/lib64/libdl.so)
-- Could NOT find FFTW3 (missing: FFTW3_DIR)
-- FindFFTW using pkgconfig: FOUND=1 LIBRARIES=fftw3;m LIBRARY_DIRS= LIBDIR=/usr/lib64 LINK_LIBRARIES=/usr/lib64/libfftw3.so;/usr/lib64/libm.so
-- FindFTTW using pkgconfig: INCLUDE_DIRS= INCLUDEDIR=/usr/include
-- FFTW found
-- Found OpenMP_C: -fopenmp
-- Found OpenMP_CXX: -fopenmp
-- Found OpenMP: TRUE
-- Looking for KenLM
-- Using kenlm library found in /usr/local/lib/libkenlm.a
-- Using kenlm utils library found in /usr/local/lib/libkenlm_util.a
-- kenlm model.hh found in /usr/local/include/kenlm/lm
-- Found kenlm (include: /usr/local/include, library: /usr/local/lib/libkenlm.a;/usr/local/lib/libkenlm_util.a;/usr/lib64/liblzma.so;/usr/lib64/libbz2.so;/usr/lib64/libz.so)
-- Could NOT find cub (missing: cub_INCLUDE_DIRS)
-- Could not find cub - will download from source
-- Configuring done
-- Generating done
-- Build files have been written to: /ceph/sz_ts80_new/zzasrli/hybrid/wave2letter/flashlight/bindings/python/build/temp.linux-x86_64-3.8
[  1%] Performing download step (git clone) for 'CUB'
[  3%] Performing update step for 'pybind11'
正克隆到 'CUB'...
[  4%] No configure step for 'pybind11'
[  6%] No build step for 'pybind11'
[  8%] No install step for 'pybind11'
[  9%] Completed 'pybind11'
[ 14%] Built target pybind11
Note: checking out 'c3cceac115c072fb63df1836ff46d8c60d9eb304'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD 目前位于 c3cceac... update readme to 1.8.0
[ 17%] No patch step for 'CUB'
[ 17%] Performing update step for 'CUB'
[ 19%] No configure step for 'CUB'
[ 20%] No build step for 'CUB'
[ 22%] No install step for 'CUB'
[ 24%] Completed 'CUB'
[ 25%] Built target CUB
Scanning dependencies of target fl-libraries
[ 27%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/CriterionUtils.cpp.o
[ 32%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/set/Hungarian.cpp.o
[ 32%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ConnectionistTemporalClassificationCriterion.cpp.o
[ 32%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ForceAlignmentCriterion.cpp.o
[ 33%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/FullConnectionCriterion.cpp.o
[ 35%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ViterbiPath.cpp.o
[ 37%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Ceplifter.cpp.o
[ 38%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Dct.cpp.o
[ 40%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Derivatives.cpp.o
[ 41%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Dither.cpp.o
[ 43%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Mfcc.cpp.o
[ 45%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Mfsc.cpp.o
[ 46%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/PowerSpectrum.cpp.o
[ 48%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/PreEmphasis.cpp.o
[ 50%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/SpeechUtils.cpp.o
[ 51%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Windowing.cpp.o
[ 53%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/TriFilterbank.cpp.o
[ 54%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/common/String.cpp.o
[ 56%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/common/System.cpp.o
[ 58%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/ConvLM.cpp.o
[ 59%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/ZeroLM.cpp.o
[ 61%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/KenLM.cpp.o
[ 62%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconDecoder.cpp.o
[ 64%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconFreeDecoder.cpp.o
[ 66%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconSeq2SeqDecoder.cpp.o
[ 67%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconFreeSeq2SeqDecoder.cpp.o
[ 69%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/Trie.cpp.o
[ 70%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/Utils.cpp.o
[ 72%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/dictionary/Dictionary.cpp.o
[ 74%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/dictionary/Utils.cpp.o
[ 75%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/tokenizer/PartialFileReader.cpp.o
[ 77%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/tokenizer/Tokenizer.cpp.o
[ 79%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu.o
[ 80%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/ForceAlignmentCriterion.cu.o
[ 82%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/FullConnectionCriterion.cu.o
[ 83%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/ViterbiPath.cu.o
[ 85%] Linking CUDA device code CMakeFiles/fl-libraries.dir/cmake_device_link.o
nvcc fatal   : Unknown option '-fopenmp'
gmake[2]: *** [CMakeFiles/fl-libraries.dir/cmake_device_link.o] 错误 1
gmake[1]: *** [CMakeFiles/fl-libraries.dir/all] 错误 2
gmake: *** [all] 错误 2
Traceback (most recent call last):
  File "setup.py", line 111, in <module>
    setup(
  File "/root/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/ceph/sz_ts80_new/zzasrli/conda_env/envs/venv_pytorch1.6/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/ceph/sz_ts80_new/zzasrli/conda_env/envs/venv_pytorch1.6/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/ceph/sz_ts80_new/zzasrli/conda_env/envs/venv_pytorch1.6/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/.local/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/root/.local/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/ceph/sz_ts80_new/zzasrli/conda_env/envs/venv_pytorch1.6/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/ceph/sz_ts80_new/zzasrli/conda_env/envs/venv_pytorch1.6/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/.local/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/root/.local/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/ceph/sz_ts80_new/zzasrli/conda_env/envs/venv_pytorch1.6/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/ceph/sz_ts80_new/zzasrli/conda_env/envs/venv_pytorch1.6/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/.local/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/ceph/sz_ts80_new/zzasrli/conda_env/envs/venv_pytorch1.6/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/ceph/sz_ts80_new/zzasrli/conda_env/envs/venv_pytorch1.6/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/ceph/sz_ts80_new/zzasrli/conda_env/envs/venv_pytorch1.6/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 56, in run
    self.build_extensions(ext)
  File "setup.py", line 108, in build_extensions
    subprocess.check_call(
  File "/ceph/sz_ts80_new/zzasrli/conda_env/envs/venv_pytorch1.6/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Comment by lizezheng** [comment]
installation without CUDA runs ok, with "export USE_CUDA=0"
while installation with CUDA stills fails !=_=

**Comment by tlikhomanenko** [comment]
what are system config do you have? OS, cuda, nvcc, gcc, cmake?
