### ISSUE TITLE
[Question title here]can not install flashlight via command python3 setup.py install

### ISSUE THREAD

**Issue by harivineesha** [flashlight/flashlight#833]
### Question
Cannot install flashlight bindings using command using python3 setup.py install 

Installing log:
running install
/anaconda3/envs/Speech-Recognisition/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/anaconda3/envs/Speech-Recognisition/lib/python3.8/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing flashlight.egg-info/PKG-INFO
writing dependency_links to flashlight.egg-info/dependency_links.txt
writing top-level names to flashlight.egg-info/top_level.txt
package init file 'flashlight/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/audio/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/sequence/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/text/__init__.py' not found (or not a regular file)
reading manifest file 'flashlight.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'flashlight.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
-- -rdynamic supported.
-- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;Threads::Threads;dl;/usr/lib64/librt.so include: /usr/local/cuda/include)
-- CUDA architecture flags: -gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_80,code=sm_80-gencodearch=compute_80,code=compute_80
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) (Required is at least version "1.10.0")
-- googletest not found - will download and build from source
-- MKL_THREADING = OMP
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib64/libpthread.so
--   Library m: /usr/lib64/libm.so
--   Library dl: /usr/lib64/libdl.so
-- MKL library found
-- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib64/libpthread.so;/usr/lib64/libm.so;/usr/lib64/libdl.so)
-- Could NOT find FFTW3 (missing: FFTW3_DIR)
-- FindFFTW using pkgconfig: FOUND=1 LIBRARIES=fftw3;m LIBRARY_DIRS= LIBDIR=/usr/lib64 LINK_LIBRARIES=/usr/lib64/libfftw3.so;/usr/lib64/libm.so
-- FindFTTW using pkgconfig: INCLUDE_DIRS= INCLUDEDIR=/usr/include
-- FFTW found
-- Looking for KenLM
-- Using kenlm library found in /usr/local/lib/libkenlm.a
-- Using kenlm utils library found in /usr/local/lib/libkenlm_util.a
-- kenlm model.hh found in /usr/local/include/kenlm/lm
-- Found kenlm (include: /usr/local/include, library: /usr/local/lib/libkenlm.a;/usr/local/lib/libkenlm_util.a;/usr/lib64/liblzma.so;/usr/lib64/libbz2.so;/usr/lib64/libz.so)
-- Configuring done
CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "fl_lib_sequence".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /root/TFCNN/transcribe/flashlight_main/bindings/python/build/temp.linux-x86_64-3.8
Consolidate compiler generated dependencies of target fl_lib_common
Consolidate compiler generated dependencies of target fl_lib_audio
Consolidate compiler generated dependencies of target fl_lib_sequence
[  1%] Performing update step (git update) for 'pybind11'
[  4%] Built target fl_lib_common
[ 17%] Built target fl_lib_audio
[ 18%] Skipping patch step (no custom command) for 'pybind11'
Consolidate compiler generated dependencies of target fl_lib_text
[ 29%] Built target fl_lib_sequence
[ 30%] Performing update step (git update) for 'gtest'
Consolidate compiler generated dependencies of target fl_lib_set
[ 31%] No configure step for 'pybind11'
[ 33%] Built target fl_lib_set
[ 44%] Skipping patch step (no custom command) for 'gtest'
[ 49%] Built target fl_lib_text
[ 50%] No build step for 'pybind11'
[ 51%] Performing configure step for 'gtest'
loading initial cache file /root/TFCNN/transcribe/flashlight_main/bindings/python/build/temp.linux-x86_64-3.8/googletest/tmp/gtest-cache-Release.cmake
CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

[ 52%] No install step for 'pybind11'
CMake Deprecation Warning at googlemock/CMakeLists.txt:45 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

[ 53%] Completed 'pybind11'
[ 55%] Built target pybind11
Consolidate compiler generated dependencies of target flashlight_lib_text_dictionary
Consolidate compiler generated dependencies of target flashlight_lib_audio_feature
Consolidate compiler generated dependencies of target flashlight_lib_text_decoder
[ 56%] Building CXX object CMakeFiles/flashlight_lib_text_dictionary.dir/bindings/python/flashlight/lib/text/_dictionary.cpp.o
-- Configuring done
[ 58%] Building CXX object CMakeFiles/flashlight_lib_audio_feature.dir/bindings/python/flashlight/lib/audio/_feature.cpp.o
[ 59%] Building CXX object CMakeFiles/flashlight_lib_text_decoder.dir/bindings/python/flashlight/lib/text/_decoder.cpp.o
-- Generating done
-- Build files have been written to: /root/TFCNN/transcribe/flashlight_main/bindings/python/build/temp.linux-x86_64-3.8/googletest/src/gtest
[ 60%] Performing build step for 'gtest'
gmake[3]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
Consolidate compiler generated dependencies of target gtest
[ 25%] Built target gtest
Consolidate compiler generated dependencies of target gmock
[ 50%] Built target gmock
Consolidate compiler generated dependencies of target gmock_main
[ 75%] Built target gmock_main
Consolidate compiler generated dependencies of target gtest_main
[100%] Built target gtest_main
[ 61%] No install step for 'gtest'
[ 62%] Completed 'gtest'
[ 64%] Built target gtest
Consolidate compiler generated dependencies of target flashlight_lib_sequence_criterion
[ 65%] Building CXX object CMakeFiles/flashlight_lib_sequence_criterion.dir/bindings/python/flashlight/lib/sequence/_criterion.cpp.o
[ 66%] Linking CXX shared module ../lib.linux-x86_64-3.8/flashlight/lib/text/flashlight_lib_text_dictionary.cpython-38-x86_64-linux-gnu.so
[ 67%] Linking CXX shared module ../lib.linux-x86_64-3.8/flashlight/lib/sequence/flashlight_lib_sequence_criterion.cpython-38-x86_64-linux-gnu.so
[ 68%] Linking CXX shared module ../lib.linux-x86_64-3.8/flashlight/lib/audio/flashlight_lib_audio_feature.cpython-38-x86_64-linux-gnu.so
[ 68%] Built target flashlight_lib_text_dictionary
Consolidate compiler generated dependencies of target DctTest
[ 69%] Building CXX object flashlight/lib/audio/test/CMakeFiles/DctTest.dir/feature/DctTest.cpp.o
[ 69%] Built target flashlight_lib_sequence_criterion
[ 70%] Building CXX object flashlight/lib/audio/test/CMakeFiles/WindowingTest.dir/feature/WindowingTest.cpp.o
[ 72%] Linking CXX shared module ../lib.linux-x86_64-3.8/flashlight/lib/text/flashlight_lib_text_decoder.cpython-38-x86_64-linux-gnu.so
[ 73%] Linking CXX executable DctTest
CMakeFiles/DctTest.dir/feature/DctTest.cpp.o: In function `DctTest_matlabCompareTest_Test::TestBody()':
DctTest.cpp:(.text+0x5d1): undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
DctTest.cpp:(.text+0x679): undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
CMakeFiles/DctTest.dir/feature/DctTest.cpp.o: In function `DctTest_batchingTest_Test::TestBody()':
DctTest.cpp:(.text+0xdd0): undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
CMakeFiles/DctTest.dir/feature/DctTest.cpp.o: In function `testing::AssertionResult testing::internal::CmpHelperEQFailure<unsigned long, int>(char const*, char const*, unsigned long const&, int const&)':
DctTest.cpp:(.text._ZN7testing8internal18CmpHelperEQFailureImiEENS_15AssertionResultEPKcS4_RKT_RKT0_[_ZN7testing8internal18CmpHelperEQFailureImiEENS_15AssertionResultEPKcS4_RKT_RKT0_]+0x922): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [flashlight/lib/audio/test/DctTest] Error 1
gmake[1]: *** [flashlight/lib/audio/test/CMakeFiles/DctTest.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 74%] Linking CXX executable WindowingTest
CMakeFiles/WindowingTest.dir/feature/WindowingTest.cpp.o: In function `WindowingTest_hanningCoeffsTest_Test::TestBody()':
WindowingTest.cpp:(.text+0x395): undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
CMakeFiles/WindowingTest.dir/feature/WindowingTest.cpp.o: In function `WindowingTest_hammingCoeffsTest_Test::TestBody()':
WindowingTest.cpp:(.text+0x9dd): undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
CMakeFiles/WindowingTest.dir/feature/WindowingTest.cpp.o: In function `WindowingTest_batchingTest_Test::TestBody()':
WindowingTest.cpp:(.text+0xcb3): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
WindowingTest.cpp:(.text+0x1083): undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [flashlight/lib/audio/test/WindowingTest] Error 1
gmake[1]: *** [flashlight/lib/audio/test/CMakeFiles/WindowingTest.dir/all] Error 2
[ 74%] Built target flashlight_lib_audio_feature
[ 74%] Built target flashlight_lib_text_decoder
gmake: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 110, in <module>
    setup(
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/site-packages/setuptools/command/install.py", line 116, in do_egg_install
    self.run_command('bdist_egg')
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 56, in run
    self.build_extensions(ext)
  File "setup.py", line 107, in build_extensions
    subprocess.check_call(
  File "/anaconda3/envs/Speech-Recognisition/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Can you please give advice.**

OS: Centos 7
Gmake : 3.82
cuda : 11.4
gcc : 7.5
cmake : 3.20

**Comment by harivineesha** [comment]
@tlikhomanenko can you please help with this?
